[versions]
kotlin = "2.1.0"
kotlin-coroutines = "1.10.1"
ajalt-clikt = "5.0.2"
touchlab-kermit = "2.0.4"
arrow = "2.0.1"
exposed = "0.58.0"
xeial-sqlite = "3.44.1.0"
lingala-zip4j = "2.11.5"

[libraries]
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
ajalt-clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "ajalt-clikt" }
touchlab-kermit = { module = "co.touchlab:kermit", version.ref = "touchlab-kermit" }
arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
arrow-coroutines = { module = "io.arrow-kt:arrow-fx-coroutines", version.ref = "arrow" }
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
exposed-kotlin-datetime = { module = "org.jetbrains.exposed:exposed-kotlin-datetime", version.ref = "exposed" }
xerial-sqlite = { module = "org.xerial:sqlite-jdbc", version.ref = "xeial-sqlite" }
lingala-zip4j = { module = "net.lingala.zip4j:zip4j", version.ref = "lingala-zip4j" }

[bundles]
arrow = ["arrow-core", "arrow-coroutines"]
exposed = ["exposed-core", "exposed-jdbc", "xerial-sqlite", "exposed-dao", "exposed-kotlin-datetime"]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
